#!/bin/bash
if [ ! -d "./env" ]; then
    echo "==========Preparing environment to start=========="
    python3 -m venv env
    source env/bin/activate
    pip install -r requirements.txt
    python src/manage.py migrate
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python src/manage.py shell
    python src/manage.py runserver 0.0.0.0:8000
else
    source env/bin/activate
    python src/manage.py runserver 0.0.0.0:8000
fi
